name: Build AMI with Packer

on:
  push:
    paths:
      - 'clearml-agent-ami/**'
      - '.github/workflows/build-clearml-agent.ami.yml'
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Initialize Packer
        run: packer init packer.json
        working-directory: clearml-agent-ami

      - name: Upgrade to HCL2
        run: packer hcl2_upgrade packer.json
        working-directory: clearml-agent-ami

      - name: Validate Packer template
        run: packer validate packer.json
        working-directory: clearml-agent-ami

      - name: Build AMI with Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          packer build \
            -var 'aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}' \
            -var 'aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            packer.json
        working-directory: clearml-agent-ami