name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Validate Terraform
        run: terraform validate
        working-directory: infra

      - name: Plan Terraform
        run: terraform plan
        working-directory: infra

      - name: Apply Terraform
        if: github.event.inputs.action == 'apply'
        id: apply
        run: |
          terraform apply -auto-approve
          echo "elastic_ip=$(terraform output -raw elastic_ip)" >> $GITHUB_OUTPUT
        working-directory: infra

      - name: Destroy Terraform
        if: github.event.inputs.action == 'destroy'
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: infra

      - name: Add SSH key to SSH agent
        if: github.event.inputs.action == 'apply'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CLEARML_DEMO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Test SSH access to EC2 instance
        if: github.event.inputs.action == 'apply'
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ steps.apply.outputs.clearml_server_ip }} 'echo "SSH connection successful"'
